export default {
	REQUEST_WEATHER_FORECASTS: 'REQUEST_WEATHER_FORECASTS',
	RECEIVE_WEATHER_FORECASTS: 'RECEIVE_WEATHER_FORECASTS',
	GET_ALL_POSTS: 'GET_ALL_POSTS',
	CREATE_POST: 'CREATE_POST',
	DELETE_POST: 'DELETE_POST',
	GETTING_ALL_POSTS: 'GETTING_ALL_POSTS',
	GET_POST: 'GET_POST', 
	CREATE_COMMENT: 'CREATE_COMMENT',
	GET_COMMENTS: 'GET_COMMENTS',
	USER_AUTHENTICATED: 'USER_AUTHENTICATED', 
	ERROR_AUTHENTICATION: 'ERROR_AUTHENTICATION',
	USERS_GET_ALL: 'USERS_GET_ALL',
	USER_UNAUTHENTICATED: 'USER_UNAUTHENTICATED', 
	ERROR_CREATE_POST: 'ERROR_CREATE_POST',
	TINY_MCE_RESET: 'TINY_MCE_RESET',

	HTTP_STATUS_OK: 200,
	HTTP_STATUS_CREATED: 201,
	HTTP_STATUS_UNAUTHORIZED: 401,
	HTTP_STATUS_BAD_REQUEST: 400, 

	ERROR_GENERIC: 'ERROR_GENERIC',
	USERS_GET_POSTS: 'USERS_GET_POSTS',
	POSTS_FAVORITED: 'POSTS_FAVORITED',
	USERS_GET_FAVORITE_POSTS: 'USERS_GET_FAVORITE_POSTS',
	USERS_REGISTERED: 'USERS_REGISTERED',

};
